- set_fact:
    config_file_path: /etc/ansible/ansible.cfg
    ansible_local_roles_path: /usr/local/src

- include_vars: "configure.yml"

- name: create local roles folder
  file:
    path: "{{ansible_local_roles_path}}/ansible/roles"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: '0755'
  become: yes

- name: create local playbooks folder
  file:
    path: "{{ansible_local_roles_path}}/ansible/playbooks"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: '0755'
  become: yes

- name: create local collections folder
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: '0755'
  loop: "{{ config.collections_paths }}"
  become: yes

- name: Set ansible config options
  lineinfile:
    path: "{{config_file_path}}"
    regexp: "^#?\\s*{{ item.key }}\\s*="
    line: "{{ item.key }} = {{ item.value }}"
  loop: "{{ ansible_config | dict2items }}"
  become: yes
  