- include_vars: "configure.yml"

- name: create local roles folder
  file:
    path: "{{ansible_local_roles_path}}/ancible/roles"
    state: directory
    mode: '0755'
  become: yes

- name: create local playbooks folder
  file:
    path: "{{ansible_local_roles_path}}/ancible/playbooks"
    state: directory
    mode: '0755'
  become: yes

- name: Set ansible config options
  lineinfile:
    path: "{{config_file_path}}"
    regexp: "^#?\\s*{{ item.key }}\\s*="
    line: "{{ item.key }} = {{ item.value }}"
  loop: "{{ ansible_config | dict2items }}"
  become: yes
  