---
- name: create local collections folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: '0755'
  loop: "{{ config.collections_paths | flatten | map('extract', config.collections_paths) | flatten }}"
  become: yes
  ignore_errors: yes

- name: create roles folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: '0755'
  loop: "{{ config.roles_path | flatten | map('extract', config.roles_path) | flatten }}"
  become: yes
  ignore_errors: yes

- name: create playbook folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: '0755'
  loop: "{{ config.playbooks_path | flatten | map('extract', config.playbooks_path) | flatten }}"
  become: yes
  ignore_errors: yes

- name: Set ansible config options
  lineinfile:
    path: "/etc/ansible/ansible.cfg"
    regexp: "^#?\\s*{{ item.key }}\\s*="
    line: "{{ item.key }} = {{ item.value }}"
  loop: "{{ ansible_config | dict2items }}"
  become: yes
  